CC := gcc
CXX := g++

SRC_DIR := src
BUILD_DIR := build

CPP_SRC_FILES := $(wildcard $(SRC_DIR)/*.cc)
# CPP_OBJ_FILES := $(patsubst $(SRC_DIR)/%.cc,$(BUILD_DIR)/%.o,$(CPP_SRC_FILES))
CPP_OBJ_FILE := $(BUILD_DIR)/cpp.o

C_SRC_FILES := $(wildcard $(SRC_DIR)/*.c)
EXE_FILE := tracesim

INC_DIR := inc

COMPILER_FLAGS_COMMON := -Wall -I$(INC_DIR)/

CPP_COMPILER_FLAGS := -std=gnu++11
C_COMPILER_FLAGS := -std=gnu99 -o $(BUILD_DIR)/$(EXE_FILE)

COMPILER_FLAGS_DEBUG := $(COMPILER_FLAGS_COMMON) -g
COMPILER_FLAGS_RELEASE := $(COMPILER_FLAGS_COMMON) -O3

LINKER_FLAGS = -lz -lstdc++

# all: debug
all: release

# $(BUILD_DIR)/%.o: $(SRC_DIR)/%.cc
# 	$(CXX) $(CPP_COMPILER_FLAGS) $(COMPILER_FLAGS_RELEASE) -c $< -o $@

# debug: build_dir $(CPP_OBJ_FILES)
# 	$(CC) $(C_COMPILER_FLAGS) $(COMPILER_FLAGS_DEBUG) $(C_SRC_FILES) $(CPP_OBJ_FILES) $(LINKER_FLAGS)

# release: build_dir $(CPP_OBJ_FILES)
# 	$(CC) $(C_COMPILER_FLAGS) $(COMPILER_FLAGS_RELEASE) $(C_SRC_FILES) $(CPP_OBJ_FILES) $(LINKER_FLAGS)

debug: build_dir
	$(CXX) $(CPP_COMPILER_FLAGS) $(COMPILER_FLAGS_DEBUG) -r $(CPP_SRC_FILES) -o $(CPP_OBJ_FILE)
	$(CC) $(C_COMPILER_FLAGS) $(COMPILER_FLAGS_DEBUG) $(C_SRC_FILES) $(CPP_OBJ_FILE) $(LINKER_FLAGS)

release: build_dir
	$(CXX) $(CPP_COMPILER_FLAGS) $(COMPILER_FLAGS_RELEASE) -r $(CPP_SRC_FILES) -o $(CPP_OBJ_FILE)
	$(CC) $(C_COMPILER_FLAGS) $(COMPILER_FLAGS_RELEASE) $(C_SRC_FILES) $(CPP_OBJ_FILE) $(LINKER_FLAGS)

build_dir:
	@mkdir -p $(BUILD_DIR)

clean:
	@rm -rf build
