CC := gcc
CXX := g++

SRC_DIR := src
BUILD_DIR := build

CPP_SRC_FILES := $(wildcard $(SRC_DIR)/*.cc)
CPP_OBJ_FILE_DEBUG := $(BUILD_DIR)/cpp_debug.o
CPP_OBJ_FILE_RELEASE := $(BUILD_DIR)/cpp_release.o

C_SRC_FILES := $(wildcard $(SRC_DIR)/*.c)
EXE_FILE := traceconv

INC_DIR := inc

COMPILER_FLAGS_COMMON := -Wall -I$(INC_DIR)/

CPP_COMPILER_FLAGS := -std=gnu++11
C_COMPILER_FLAGS := -std=gnu99 -o $(BUILD_DIR)/$(EXE_FILE)

COMPILER_FLAGS_DEBUG := $(COMPILER_FLAGS_COMMON) -g
COMPILER_FLAGS_RELEASE := $(COMPILER_FLAGS_COMMON) -O3

LINKER_FLAGS = -lz -lstdc++ # TODO remove C++?

# all: debug
all: release

$(CPP_OBJ_FILE_DEBUG): $(CPP_SRC_FILES)
	$(CXX) $(CPP_COMPILER_FLAGS) $(COMPILER_FLAGS_DEBUG) -r $^ -o $@

$(CPP_OBJ_FILE_RELEASE): $(CPP_SRC_FILES)
	$(CXX) $(CPP_COMPILER_FLAGS) $(COMPILER_FLAGS_RELEASE) -r $^ -o $@

debug: build_dir $(CPP_OBJ_FILE_DEBUG)
	$(CC) $(C_COMPILER_FLAGS) $(COMPILER_FLAGS_DEBUG) $(C_SRC_FILES) $(CPP_OBJ_FILE_DEBUG) $(LINKER_FLAGS)

release: build_dir $(CPP_OBJ_FILE_RELEASE)
	$(CC) $(C_COMPILER_FLAGS) $(COMPILER_FLAGS_RELEASE) $(C_SRC_FILES) $(CPP_OBJ_FILE_RELEASE) $(LINKER_FLAGS)

build_dir:
	@mkdir -p $(BUILD_DIR)

clean:
	@rm -rf build
